(() => {
  'use strict';const OS=window.Aether;
  OS.Browser=Object.freeze({launch(services){
    const content=document.createElement('div');content.className='browser-app';content.innerHTML='<div class="browser-tabs"></div><form class="app-toolbar browser-bar"><button type="button" data-action="back" aria-label="Browser back">←</button><button type="button" data-action="forward" aria-label="Browser forward">→</button><button type="button" data-action="refresh">Refresh</button><button type="button" data-action="home">Home</button><input aria-label="Address or search" placeholder="Address or search"><button>Go</button><button type="button" data-action="bookmark">Bookmark</button></form><div class="app-toolbar"><button data-action="bookmarks">Bookmarks</button><button data-action="history">History</button></div><div class="browser-page"></div>';
    const $=s=>content.querySelector(s),data=services.storage.data;let tabs=[{id:crypto.randomUUID(),stack:['aether://home'],index:0}],active=tabs[0].id,disposed=false,revision=0;
    const tab=()=>tabs.find(t=>t.id===active),address=()=>tab().stack[tab().index];
    function normalize(value){value=value.trim();if(!value)return 'aether://home';if(value.startsWith('aether://'))return value;if(/^[a-z][a-z0-9+.-]*:/i.test(value)){const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw Error('Only http, https, and Aether pages are supported.');return url.href;}if(!/\s/.test(value)&&value.includes('.'))return new URL('https://'+value).href;return 'https://www.google.com/search?q='+encodeURIComponent(value);}
    async function visit(value){try{const url=normalize(value),t=tab();t.stack=t.stack.slice(0,t.index+1).concat(url);t.index++;render();await data.update('browser:history',items=>[{url,time:Date.now()},...(items||[])].slice(0,150));}catch(error){$('.browser-page').textContent=error.message;}}
    function text(tag,value,parent=$('.browser-page')){const el=document.createElement(tag);el.textContent=value;parent.append(el);return el;}
    function render(){if(disposed)return;revision++;const url=address();$('.browser-bar input').value=url;$('.browser-tabs').replaceChildren();for(const t of tabs){const group=document.createElement('span');group.className='browser-tab';const select=document.createElement('button');select.textContent=t.stack[t.index].replace(/^https?:\/\//,'');select.setAttribute('aria-pressed',String(t.id===active));select.onclick=()=>{active=t.id;render();};const close=document.createElement('button');close.textContent='×';close.setAttribute('aria-label','Close tab');close.onclick=()=>{tabs=tabs.filter(x=>x!==t);if(!tabs.length)tabs.push({id:crypto.randomUUID(),stack:['aether://home'],index:0});if(active===t.id)active=tabs.at(-1).id;render();};group.append(select,close);$('.browser-tabs').append(group);}const add=document.createElement('button');add.textContent='+';add.setAttribute('aria-label','New tab');add.onclick=()=>{const t={id:crypto.randomUUID(),stack:['aether://home'],index:0};tabs.push(t);active=t.id;render();};$('.browser-tabs').append(add);
      $('[data-action="back"]').disabled=tab().index===0;$('[data-action="forward"]').disabled=tab().index===tab().stack.length-1;$('.browser-page').replaceChildren();
      if(url==='aether://home'){text('h2','Aether Browser');text('p','A local browsing workspace. Enter an address or search above.');for(const name of ['about','help']){const b=text('button',name==='about'?'About this browser':'Navigation help');b.onclick=()=>visit('aether://'+name);}}
      else if(url==='aether://about'){text('h2','About Aether Browser');text('p','Tabs, bookmarks, and local history run inside Aether OS. This version does not embed or fetch websites.');}
      else if(url==='aether://help'){text('h2','Navigation help');text('p','Use Back, Forward, Refresh, or Home. Web addresses and searches display a handoff page; open the link to continue in your actual browser.');}
      else if(url.startsWith('aether://')){text('h2','Page not found');text('p',url);}
      else{text('h2','Open on the web');text('p','Simulated browser page — this website has not been loaded inside Aether.');text('p',url);const link=text('a','Open in external tab');link.href=url;link.target='_blank';link.rel='noopener noreferrer';}
    }
    async function listing(kind){const ticket=++revision;try{const items=await data.get('browser:'+kind)||[];if(disposed||ticket!==revision)return;const page=$('.browser-page');page.replaceChildren();text('h2',kind==='history'?'History':'Bookmarks');if(!items.length)text('p','Nothing saved yet.');for(const item of items){const row=document.createElement('div');row.className='browser-saved';const go=document.createElement('button');go.textContent=item.url;go.onclick=()=>visit(item.url);const remove=document.createElement('button');remove.textContent='Remove';remove.onclick=async()=>{try{await data.update('browser:'+kind,items=>(items||[]).filter(n=>n.url!==item.url));listing(kind);}catch(error){services.notify(error.message);}};row.append(go,remove);page.append(row);}}catch(error){$('.browser-page').textContent=error.message;}}
    const actions={back:()=>{if(tab().index>0){tab().index--;render();}},forward:()=>{if(tab().index<tab().stack.length-1){tab().index++;render();}},refresh:render,home:()=>visit('aether://home'),bookmark:async()=>{const url=address();try{await data.update('browser:bookmarks',items=>[{url},...(items||[]).filter(n=>n.url!==url)].slice(0,100));services.notify({title:'Browser',message:'Bookmark saved.'});}catch(error){services.notify(error.message);}},bookmarks:()=>listing('bookmarks'),history:()=>listing('history')};
    content.querySelectorAll('[data-action]').forEach(b=>b.onclick=actions[b.dataset.action]);content.querySelector('form').onsubmit=e=>{e.preventDefault();visit($('.browser-bar input').value);};render();return{content,dispose(){disposed=true;}};
  }});
})();
