/* Notes owns content only; persistence and window lifecycle are OS services. */
(() => {
  'use strict';const OS=window.Aether,KEY='notes:workspace';
  const initial=()=>({version:1,folders:[],notes:[]});
  OS.Notes=Object.freeze({launch(services){const data=services.storage.data,content=document.createElement('div');content.className='notes-app';
    content.innerHTML='<aside class="notes-sidebar"><input class="notes-search" type="search" aria-label="Search notes" placeholder="Search notes…"><select class="notes-filter" aria-label="Notes folder"></select><div class="notes-create"><input class="notes-folder-name" aria-label="New folder name" placeholder="Folder name"><button class="notes-new-folder">New folder</button></div><button class="notes-delete-folder">Delete folder</button><button class="notes-new">+ New note</button><div class="notes-list"></div></aside><section class="notes-editor"><div class="notes-heading"><input class="notes-title" aria-label="Note title" placeholder="Note title"><button class="notes-pin">Pin</button><button class="notes-delete">Delete</button></div><label>Move to folder <select class="notes-destination" aria-label="Note destination"></select></label><textarea class="notes-body" aria-label="Note text" placeholder="Write a note…"></textarea><p class="notes-status" role="status">Loading notes…</p></section>';
    const $=s=>content.querySelector(s);let workspace=initial(),displayed=null,selected=null,folder='all',expected=0,dirty=false,pending=0,disposed=false,queue=Promise.resolve(),failed=false,pinned=false,renderToken=0;
    const status=text=>$('.notes-status').textContent=text;
    const nameOK=name=>{if(!name.trim()||name.trim().length>120)throw Error('Enter a name of 1–120 characters.');return name.trim();};
    const path=id=>{const parts=[];let f=workspace.folders.find(f=>f.id===id);while(f){parts.unshift(f.name);f=workspace.folders.find(p=>p.id===f.parent);}return ['Notes',...parts].join(' / ');};
    function folderOptions(select,allOption=false){const prev=select.value;select.replaceChildren();for(const[id,label]of [...(allOption?[['all','All notes']]:[]),['root','Notes'],...workspace.folders.map(f=>[f.id,path(f.id)])]){const opt=document.createElement('option');opt.value=id;opt.textContent=label;select.append(opt);}select.value=[...select.options].some(o=>o.value===prev)?prev:allOption?'all':'root';}
    function editor(note){displayed=note?.id||null;selected=note?.id||null;expected=note?.revision||0;pinned=!!note?.pinned;$('.notes-title').value=note?.title||'';$('.notes-body').value=note?.body||'';$('.notes-destination').value=note?.folder||'root';$('.notes-pin').textContent=pinned?'Unpin':'Pin';$('.notes-pin').setAttribute('aria-pressed',String(pinned));content.querySelectorAll('.notes-editor input,.notes-editor textarea,.notes-editor button,.notes-editor select').forEach(el=>el.disabled=!note);status(note?'Saved':'Create or select a note.');}
    async function render(){const token=++renderToken;try{const value=await data.get(KEY);if(disposed||token!==renderToken)return;workspace=value||initial();folderOptions($('.notes-filter'),true);folderOptions($('.notes-destination'));if(folder!=='all'&&folder!=='root'&&!workspace.folders.some(f=>f.id===folder))folder='all';$('.notes-filter').value=folder;$('.notes-delete-folder').disabled=['root','all'].includes(folder);
      const query=$('.notes-search').value.trim().toLowerCase();const ids=new Set([folder]);let count;do{count=ids.size;workspace.folders.forEach(f=>{if(ids.has(f.parent))ids.add(f.id);});}while(count!==ids.size);
      const matches=workspace.notes.filter(n=>(folder==='all'||ids.has(n.folder))&&`${n.title} ${n.body}`.toLowerCase().includes(query)).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.modified-a.modified);
      $('.notes-list').replaceChildren(...matches.map(note=>{const b=document.createElement('button');b.className='notes-item';b.dataset.note=note.id;b.setAttribute('aria-pressed',String(note.id===selected));b.textContent=(note.pinned?'★ ':'')+note.title;const detail=document.createElement('small');detail.textContent=path(note.folder);b.append(detail);b.addEventListener('click',()=>selectNote(note.id));return b;}));
      if(!matches.length){const p=document.createElement('p');p.textContent=query?'No matching notes.':'No notes here yet.';$('.notes-list').append(p);}if(!dirty&&!pending){const note=workspace.notes.find(n=>n.id===selected);if((note?.id||null)!==displayed||(note?.revision||0)!==expected)editor(note);}
    }catch(error){status(error.message);}}
    async function flush(){await queue;if(dirty){if(!confirm('This note has unsaved changes. Discard them and continue?'))return false;dirty=false;failed=false;}return true;}
    async function selectNote(id){if(!await flush())return;const value=await data.get(KEY);workspace=value||initial();editor(workspace.notes.find(n=>n.id===id));render();}
    function autosave(){if(!selected)return;dirty=true;status('Saving…');if(failed){status('Save conflict or storage error. Copy your text, then reselect the note to reload.');return;}const id=selected,snapshot={title:$('.notes-title').value.trim()||'Untitled',body:$('.notes-body').value,folder:$('.notes-destination').value,pinned};pending++;queue=queue.then(async()=>{if(failed)return;try{const result=await data.update(KEY,value=>{const w=value||initial(),note=w.notes.find(n=>n.id===id);if(!note)throw Error('This note was deleted in another window.');if(note.revision!==expected)throw Error('This note changed in another window. Your text has not been overwritten.');if(snapshot.folder!=='root'&&!w.folders.some(f=>f.id===snapshot.folder))throw Error('The destination folder was deleted.');Object.assign(note,snapshot,{revision:note.revision+1,modified:Date.now()});return w;});expected=result.notes.find(n=>n.id===id).revision;}catch(error){failed=true;status(error.message+' Copy your text before reselecting this note.');}}).finally(()=>{pending--;if(!pending&&!failed){dirty=false;status('Saved');render();}});}
    async function mutate(fn){if(!await flush())return;try{workspace=await data.update(KEY,fn);await render();}catch(error){status(error.message);}}
    $('.notes-new').addEventListener('click',()=>mutate(w=>{w=w||initial();if(folder!=='all'&&folder!=='root'&&!w.folders.some(f=>f.id===folder))throw Error('This folder was deleted. Choose another folder.');const id=crypto.randomUUID();w.notes.push({id,title:'Untitled',body:'',folder:folder==='all'?'root':folder,pinned:false,revision:1,modified:Date.now()});selected=id;return w;}));
    $('.notes-new-folder').addEventListener('click',()=>mutate(w=>{w=w||initial();const name=nameOK($('.notes-folder-name').value),parent=folder==='all'?'root':folder;if(parent!=='root'&&!w.folders.some(f=>f.id===parent))throw Error('Parent folder was deleted.');if(w.folders.some(f=>f.parent===parent&&f.name.toLowerCase()===name.toLowerCase()))throw Error('A folder with this name already exists.');const id=crypto.randomUUID();w.folders.push({id,name,parent});folder=id;$('.notes-folder-name').value='';return w;}));
    $('.notes-delete-folder').addEventListener('click',async()=>{if(!confirm('Delete this Notes folder, its subfolders, and all notes inside?'))return;await mutate(w=>{const ids=new Set([folder]);let count;do{count=ids.size;w.folders.forEach(f=>{if(ids.has(f.parent))ids.add(f.id);});}while(count!==ids.size);w.folders=w.folders.filter(f=>!ids.has(f.id));w.notes=w.notes.filter(n=>!ids.has(n.folder));folder='all';return w;});});
    $('.notes-delete').addEventListener('click',async()=>{if(!confirm('Delete this note permanently?'))return;await mutate(w=>{w.notes=w.notes.filter(n=>n.id!==selected);selected=null;return w;});});
    $('.notes-pin').addEventListener('click',()=>{pinned=!pinned;$('.notes-pin').textContent=pinned?'Unpin':'Pin';$('.notes-pin').setAttribute('aria-pressed',String(pinned));autosave();});
    for(const selector of ['.notes-title','.notes-body'])$(selector).addEventListener('input',autosave);$('.notes-destination').addEventListener('change',autosave);
    $('.notes-filter').addEventListener('change',()=>{folder=$('.notes-filter').value;render();});$('.notes-search').addEventListener('input',render);
    const off=services.storage.subscribe(render);const unload=e=>{if((dirty||pending)&&!services.storage.wasReplaced){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);
    data.update(KEY,value=>value||initial()).then(render).catch(error=>status(error.message));editor(null);
    return{content,beforeClose(){if(pending){services.notify('Notes is saving. Please try closing again in a moment.');return false;}return !dirty||confirm('Discard the unsaved note changes?');},dispose(){disposed=true;off();window.removeEventListener('beforeunload',unload);}};
  }});
})();