(() => {
  'use strict'; const OS = window.Aether;
  OS.Photos = Object.freeze({launch(services) {
    const fs=services.storage.fs, content=document.createElement('div'); content.className='photos-app';
    content.innerHTML='<div class="app-toolbar"><label class="import-photos">Import images<input type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif" aria-label="Import images"></label><select class="photo-album" aria-label="Album"></select><input class="album-name" placeholder="Album name" aria-label="New album name"><button data-action="album">New album</button><button data-action="favorites" aria-pressed="false">Favorites</button></div><p class="photo-status" role="status">Import your own images to get started.</p><div class="photo-gallery"></div><section class="photo-viewer" hidden><div class="app-toolbar"><button data-action="gallery">Gallery</button><button data-action="previous" aria-label="Previous image">←</button><button data-action="next" aria-label="Next image">→</button><button data-action="out">Zoom −</button><button data-action="in">Zoom +</button><button data-action="rotate">Rotate</button><button data-action="favorite">Favorite</button><button data-action="fullscreen">Fullscreen</button><button data-action="slideshow">Slideshow</button><select class="photo-destination" aria-label="Move image to album"></select><button data-action="move">Move</button></div><div class="photo-stage"><img alt=""></div><p class="photo-caption"></p></section>';
    const $=s=>content.querySelector(s);let images=[],filtered=[],selected=services.initialFile||null,album='all',favorites=false,zoom=1,timer=null,disposed=false,token=0,importing=false;
    const status=message=>$('.photo-status').textContent=message;
    const imageFile=n=>n.type==='file'&&/^image\/(png|jpeg|webp|gif)$/.test(n.mime||'');
    function stop(){clearInterval(timer);timer=null;content.querySelector('[data-action="slideshow"]').textContent='Slideshow';}
    function show(id){const n=images.find(n=>n.id===id);if(!n)return;selected=id;$('.photo-gallery').hidden=true;$('.photo-viewer').hidden=false;const img=$('.photo-stage img');img.src=n.content;img.alt=n.name;img.style.transform=`scale(${zoom}) rotate(${n.imageMeta?.rotation||0}deg)`;$('.photo-caption').textContent=`${n.name} · ${Math.round(zoom*100)}%`;content.querySelector('[data-action="favorite"]').textContent=n.imageMeta?.favorite?'Unfavorite':'Favorite';$('.photo-destination').value=n.parent;}
    function step(direction){if(!filtered.length){stop();return;}zoom=1;show(filtered[(Math.max(0,filtered.findIndex(n=>n.id===selected))+direction+filtered.length)%filtered.length].id);}
    async function render(){const ticket=++token;try{const nodes=await fs.all();if(disposed||ticket!==token)return;images=nodes.filter(imageFile);const albums=nodes.filter(n=>n.type==='folder'&&(n.id==='pictures'||n.parent==='pictures'));
      for(const selector of ['.photo-album','.photo-destination']){const el=$(selector),old=el.value;el.replaceChildren();if(selector==='.photo-album'){const opt=new Option('All images','all');el.add(opt);}albums.forEach(n=>el.add(new Option(n.name,n.id)));el.value=[...el.options].some(o=>o.value===old)?old:selector==='.photo-album'?'all':'pictures';}
      album=$('.photo-album').value;filtered=images.filter(n=>(album==='all'||n.parent===album)&&(!favorites||n.imageMeta?.favorite));const gallery=$('.photo-gallery');gallery.replaceChildren();for(const n of filtered){const b=document.createElement('button');b.className='photo-tile';b.dataset.file=n.id;const img=document.createElement('img');img.src=n.content;img.alt='';img.loading='lazy';const label=document.createElement('span');label.textContent=(n.imageMeta?.favorite?'★ ':'')+n.name;b.append(img,label);b.onclick=()=>{zoom=1;show(n.id);};gallery.append(b);}if(!filtered.length)gallery.textContent='No images in this view.';
      if(selected&&images.some(n=>n.id===selected))show(selected);else{selected=null;stop();gallery.hidden=false;$('.photo-viewer').hidden=true;}
    }catch(error){status(error.message);}}
    async function act(fn){try{await fn();}catch(error){status(error.message);}}
    const actions={album:()=>act(async()=>{await fs.create('pictures',$('.album-name').value,'folder');$('.album-name').value='';}),favorites:()=>{favorites=!favorites;content.querySelector('[data-action="favorites"]').setAttribute('aria-pressed',String(favorites));selected=null;stop();render();},gallery:()=>{selected=null;stop();$('.photo-viewer').hidden=true;$('.photo-gallery').hidden=false;},previous:()=>step(-1),next:()=>step(1),in:()=>{zoom=Math.min(4,zoom+.25);show(selected);},out:()=>{zoom=Math.max(.25,zoom-.25);show(selected);},rotate:()=>act(async()=>{const n=await fs.get(selected);await fs.setImageMeta(selected,{rotation:((n.imageMeta?.rotation||0)+90)%360});}),favorite:()=>act(async()=>{const n=await fs.get(selected);await fs.setImageMeta(selected,{favorite:!n.imageMeta?.favorite});}),fullscreen:()=>act(async()=>{if(document.fullscreenElement===content)await document.exitFullscreen();else if(content.requestFullscreen)await content.requestFullscreen();else status('Fullscreen is unavailable in this browser.');}),slideshow:()=>{if(timer)stop();else{timer=setInterval(()=>step(1),3000);content.querySelector('[data-action="slideshow"]').textContent='Stop slideshow';}},move:()=>act(()=>fs.transfer(selected,$('.photo-destination').value))};
    content.querySelectorAll('[data-action]').forEach(b=>b.onclick=actions[b.dataset.action]);$('.photo-album').onchange=()=>{selected=null;stop();render();};
    content.querySelector('input[type=file]').onchange=async e=>{if(importing)return;importing=true;const picker=e.target;picker.disabled=true;let count=0;try{for(const file of [...picker.files]){if(disposed)break;status(`Importing ${file.name}…`);try{if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type)||file.size>5*1024*1024)throw Error('Choose PNG, JPEG, WebP, or GIF images up to 5 MB each.');const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read image.'));reader.readAsDataURL(file);});const probe=new Image();probe.src=url;await probe.decode();if(probe.naturalWidth*probe.naturalHeight>40000000)throw Error('Image exceeds 40 megapixels.');await fs.createImage(album==='all'?'pictures':album,file.name,file.type,url);count++;}catch(error){status(`${file.name}: ${error.message}`);services.notify({title:'Photos',message:`Could not import ${file.name}: ${error.message}`});}}if(count){status(`Imported ${count} image(s) into Aether Volume.`);services.notify({title:'Photos',message:`Imported ${count} image(s).`});}}finally{importing=false;picker.disabled=false;picker.value='';}};
    const off=services.storage.subscribe(render);render();return{content,beforeClose:()=>!importing||(services.notify('Wait for image import to finish.'),false),dispose(){disposed=true;stop();off();if(document.fullscreenElement===content)document.exitFullscreen().catch(()=>{});}};
  }});
})();