/* Typed desktop preferences, applied through one OS-level interface. */
(() => {
  'use strict';
  const OS=window.Aether;
  const defaults={mode:'dark',accent:'#8b6bff',wallpaper:'nebula',transparency:8,blur:18,scale:100,iconSize:46,showIcons:true,taskbar:'normal',taskLabels:true,clock:'12',animations:true,snapping:true,windowSize:'app'};
  const choices={mode:['light','dark'],wallpaper:['nebula','midnight','aurora','eclipse'],taskbar:['normal','compact'],clock:['12','24'],windowSize:['app','small','medium','large']};
  const ranges={transparency:[0,35],blur:[0,30],scale:[80,140],iconSize:[32,64]};
  const listeners=new EventTarget();
  function read(){const raw=OS.Store.get('osSettings',{}), result={...defaults};if(raw&&typeof raw==='object')for(const key of Object.keys(defaults)){const v=raw[key];if(choices[key]?.includes(v)||ranges[key]&&typeof v==='number'&&v>=ranges[key][0]&&v<=ranges[key][1]||typeof defaults[key]==='boolean'&&typeof v==='boolean'||key==='accent'&&/^#[0-9a-f]{6}$/i.test(v))result[key]=v;}if(!raw?.accent&&OS.Store.get('theme')==='blue')result.accent='#4f8dff';result.wallpaper=OS.Store.get('wallpaper',result.wallpaper);return result;}
  function apply(){const s=read(),root=document.documentElement;root.dataset.mode=s.mode;root.dataset.motion=s.animations?'on':'off';root.dataset.taskLabels=String(s.taskLabels);root.dataset.theme='custom';root.style.setProperty('--accent-violet',s.accent);root.style.setProperty('--accent-blue',s.accent);root.style.setProperty('--surface-alpha',String(1-s.transparency/100));root.style.setProperty('--surface-blur',s.blur+'px');root.style.setProperty('--ui-scale',s.scale/100);root.style.setProperty('--desktop-icon-size',s.iconSize+'px');root.style.setProperty('--taskbar-h',Math.round((s.taskbar==='compact'?48:60)*s.scale/100)+'px');document.getElementById('icons-layer').hidden=!s.showIcons;OS.Wallpaper.init();OS.Clock?.refresh();OS.Icons?.render();window.dispatchEvent(new Event('resize'));listeners.dispatchEvent(new Event('change'));}
  OS.Settings=Object.freeze({get:read,defaults,set(key,value){if(!(key in defaults))throw Error('Unknown setting');const next={...read(),[key]:value};if(!OS.Store.set('osSettings',next))return;if(key==='wallpaper')OS.Store.set('wallpaper',value);apply();},apply,subscribe(fn){listeners.addEventListener('change',fn);return()=>listeners.removeEventListener('change',fn);},windowDefaults(){const size=read().windowSize;return {small:{width:560,height:400,maximized:false},medium:{width:800,height:560,maximized:false},large:{width:1000,height:700,maximized:false}}[size]||{};}});
  OS.applyAppearance=apply;
  OS.SettingsApp=Object.freeze({launch(services){const base=OS.StorageSettings.launch(services),content=base.content;const panel=document.createElement('section');panel.className='preferences-panel';panel.innerHTML='<h2>Settings</h2><p>Customize this Aether desktop.</p>';const fields=[['Appearance',[['mode','Color mode','select'],['accent','Accent color','color'],['wallpaper','Wallpaper','select'],['transparency','Transparency','range'],['blur','Blur','range'],['scale','UI scale','range']]],['Desktop',[['iconSize','Desktop icon size','range'],['showIcons','Show desktop icons','checkbox'],['taskbar','Taskbar height','select'],['taskLabels','Taskbar app labels','checkbox'],['clock','Clock format','select']]],['Windows',[['animations','Enable animations','checkbox'],['snapping','Snap windows at screen edges','checkbox'],['windowSize','Default size for newly opened windows','select']]]];
    for(const[title,group]of fields){const h=document.createElement('h3');h.textContent=title;panel.append(h);for(const[key,label,type]of group){const row=document.createElement('label');row.className='preference-row';const text=document.createElement('span');text.textContent=label;const input=document.createElement(type==='select'?'select':'input');input.dataset.setting=key;input.setAttribute('aria-label',label);if(type==='select')for(const value of choices[key]){const option=document.createElement('option');option.value=value;option.textContent=value==='app'?'App recommended':value;input.append(option);}else{input.type=type;if(type==='range'){input.min=ranges[key][0];input.max=ranges[key][1];input.step=key==='scale'?10:1;}}const output=document.createElement('output');row.append(text,input,output);panel.append(row);input.addEventListener('input',()=>OS.Settings.set(key,type==='checkbox'?input.checked:type==='range'?Number(input.value):input.value));}}
    function sync(){const s=read();panel.querySelectorAll('[data-setting]').forEach(el=>{const key=el.dataset.setting;if(el.type==='checkbox')el.checked=s[key];else el.value=s[key];el.nextElementSibling.textContent=el.type==='range'?`${s[key]}${['scale','transparency'].includes(key)?'%':'px'}`:'';});}content.prepend(panel);sync();const off=OS.Settings.subscribe(sync);return{...base,dispose(){off();base.dispose();}};}});
})();