(() => {
  'use strict';const OS=window.Aether;
  OS.SystemMonitor=Object.freeze({launch(services){
    const content=document.createElement('div');content.className='system-monitor';content.innerHTML='<h2>System Monitor</h2><p>Aether activity and browser-reported information.</p><dl class="monitor-metrics"></dl><h3>Open windows / running applications</h3><div class="monitor-windows"></div><p class="monitor-status" role="status"></p>';
    let disposed=false,busy=false,last=performance.now(),delay=0;
    function metric(label,value){const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=value;content.querySelector('dl').append(dt,dd);}
    async function refresh(){if(busy||disposed)return;busy=true;try{const usage=await services.storage.usage();if(disposed)return;content.querySelector('dl').replaceChildren();metric('Hardware CPU usage','Unavailable to this browser');metric('Aether timer delay',Math.round(delay)+' ms (event-loop scheduling, not CPU %)');const memory=performance.memory;metric('Browser JS heap',memory?OS.formatBytes(memory.usedJSHeapSize)+' used; '+OS.formatBytes(memory.jsHeapSizeLimit)+' limit (browser estimate, not total RAM)':'Unavailable in this browser');metric('Logical processors',navigator.hardwareConcurrency?`${navigator.hardwareConcurrency} reported by browser`:'Unavailable');metric('Aether volume',OS.formatBytes(usage.volumeBytes+usage.contentBytes));metric('Browser origin storage',usage.browserQuota?`${OS.formatBytes(usage.browserUsage||0)} / ${OS.formatBytes(usage.browserQuota)} estimated quota`:'Estimate unavailable');metric('Network hint',navigator.onLine?'Browser reports online (not a connectivity test)':'Browser reports offline');metric('Viewport',`${innerWidth} × ${innerHeight} CSS pixels`);
      const list=content.querySelector('.monitor-windows');list.replaceChildren();const ids=OS.WindowManager.listWindows();metric('Open windows',String(ids.length));for(const id of ids){const state=OS.WindowManager.getWindow(id),row=document.createElement('div');const title=document.getElementById(id)?.querySelector('.window-title')?.textContent||id;row.textContent=title+' — '+(state.minimized?'minimized':state.focused?'focused':'open');list.append(row);}content.querySelector('.monitor-status').textContent='Updated '+new Date().toLocaleTimeString();
    }catch(error){content.querySelector('.monitor-status').textContent=error.message;}finally{busy=false;}}
    const timer=setInterval(()=>{const now=performance.now();delay=Math.max(0,now-last-2000);last=now;refresh();},2000);refresh();return{content,dispose(){disposed=true;clearInterval(timer);}};
  }});
})();
