/* Simulated command interpreter: only the injected Aether virtual filesystem is used. */
(() => {
  'use strict';const OS=window.Aether;
  function tokenize(line){const tokens=[];let value='',quote=null,started=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='\\'&&quote!=="'"){if(i+1===line.length)throw Error('Trailing escape');value+=line[++i];started=true;}else if(quote){if(c===quote)quote=null;else value+=c;}else if(c==='"'||c==="'"){quote=c;started=true;}else if(/\s/.test(c)){if(started){tokens.push(value);value='';started=false;}}else{value+=c;started=true;}}if(quote)throw Error('Unclosed quote');if(started)tokens.push(value);return tokens;}
  OS.Terminal=Object.freeze({launch(services){const fs=services.storage.fs,content=document.createElement('div');content.className='terminal-app';content.innerHTML='<div class="terminal-output" role="log" aria-live="polite"></div><form class="terminal-form"><label class="terminal-prompt" for=""></label><input aria-label="Terminal command" autocomplete="off" spellcheck="false"><button>Run</button></form>';const log=content.querySelector('.terminal-output'),input=content.querySelector('input'),prompt=content.querySelector('label');let cwd='home',busy=false,disposed=false,history=[],cursor=0;
    const print=text=>{const line=document.createElement('pre');line.textContent=String(text);log.append(line);while(log.children.length>500)log.firstChild.remove();log.scrollTop=log.scrollHeight;};
    async function path(id){const nodes=await fs.all();let n=nodes.find(n=>n.id===id),parts=[];if(!n)throw Error('Current folder no longer exists. Use cd /Home.');while(n){parts.unshift(n.name);n=nodes.find(p=>p.id===n.parent);}return '/'+parts.join('/');}
    async function resolve(value='.',parentOnly=false){if(value==='~')value='/Home';if(value.startsWith('~/'))value='/Home/'+value.slice(2);let parts=value.split('/').filter(Boolean),id=value.startsWith('/')?'home':cwd;if(value.startsWith('/')&&parts[0]?.toLowerCase()==='home')parts.shift();const leaf=parentOnly?parts.pop():null;if(parentOnly&&(!leaf||leaf==='.'||leaf==='..'))throw Error('Supply a file or folder name');for(const part of parts){if(part==='.')continue;if(part==='..'){id=(await fs.get(id)).parent||'home';continue;}const item=(await fs.list(id)).find(n=>n.name===part);if(!item)throw Error(`Not found: ${part}`);id=item.id;const n=await fs.get(id);if(n.type!=='folder'&&part!==parts.at(-1))throw Error('Not a folder');}return parentOnly?{parent:id,name:leaf}:await fs.get(id);}
    async function execute(line){const [command,...args]=tokenize(line);if(!command)return;const arity=(min,max=min)=>{if(args.length<min||args.length>max)throw Error(`Invalid arguments. Type help for ${command} usage.`);};switch(command){
      case 'help':print('Aether virtual terminal — no host commands are executed.\nhelp | clear | date | whoami | neofetch\npwd | ls [path] | cd [path]\nmkdir <path> | touch <path> | rm [-r] <path>\ncat <path> | echo <text>\necho <text> > <path> (replace) or >> <path> (append)\nUse quotes for names with spaces. / and ~ mean /Home.');break;
      case 'clear':arity(0);log.replaceChildren();break;
      case 'pwd':arity(0);print(await path(cwd));break;
      case 'cd':{arity(0,1);const n=await resolve(args[0]||'/Home');if(n.type!=='folder')throw Error('Not a folder');cwd=n.id;break;}
      case 'ls':{arity(0,1);const n=await resolve(args[0]||'.');if(n.type==='file'){print(n.name);break;}print((await fs.list(n.id)).sort((a,b)=>a.name.localeCompare(b.name)).map(n=>n.name+(n.type==='folder'?'/':'')).join('\n')||'(empty)');break;}
      case 'mkdir':{arity(1);const dest=await resolve(args[0],true);await fs.create(dest.parent,dest.name,'folder');break;}
      case 'touch':{arity(1);const dest=await resolve(args[0],true);const found=(await fs.list(dest.parent)).find(n=>n.name===dest.name);if(found){if(found.type!=='file')throw Error('Not a text file');await fs.write(found.id,found.content,found.modified);}else await fs.create(dest.parent,dest.name,'file');break;}
      case 'rm':{arity(1,2);const recursive=args[0]==='-r';if(recursive&&args.length!==2)throw Error('Use rm -r <path>');if(args.length===2&&!recursive)throw Error('Use rm [-r] <path>');const n=await resolve(args[recursive?1:0]);if(n.type==='folder'&&!recursive)throw Error('Use rm -r to delete a folder and its contents');await fs.delete(n.id);break;}
      case 'cat':{arity(1);const n=await resolve(args[0]);if(n.type!=='file')throw Error('Not a text file');print(n.content);break;}
      case 'echo':{const index=args.findIndex(a=>a==='>'||a==='>>');if(index<0){print(args.join(' '));break;}if(index!==args.length-2)throw Error('Use echo <text> > <path>');const dest=await resolve(args[index+1],true),text=args.slice(0,index).join(' ')+'\n';const found=(await fs.list(dest.parent)).find(n=>n.name===dest.name);if(found){if(found.type!=='file')throw Error('Not a text file');await fs.write(found.id,(args[index]==='>>'?found.content:'')+text,found.modified);}else await fs.create(dest.parent,dest.name,'file',text);break;}
      case 'date':arity(0);print(new Date().toLocaleString());break;
      case 'whoami':arity(0);print('aether-user');break;
      case 'neofetch':{arity(0);const u=await services.storage.usage();print(`   /\\    Aether OS\n  /__\\   Browser desktop · Phase 5\n /    \\  User: aether-user\n         Volume: ${OS.formatBytes(u.volumeBytes+u.contentBytes)}\n         Files: ${u.files}\n         Shell: Aether virtual terminal`);break;}
      default:throw Error(`Unknown command: ${command}. Type help.`);
    }}
    async function updatePrompt(){try{prompt.textContent=`${await path(cwd)} $`;}catch{prompt.textContent='[folder removed] $';}}
    content.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!input.value.trim())return;const line=input.value;input.value='';history.push(line);cursor=history.length;busy=true;input.disabled=true;print('$ '+line);try{await execute(line);}catch(error){print('Error: '+error.message);}finally{busy=false;if(!disposed){await updatePrompt();input.disabled=false;input.focus();}}});
    input.addEventListener('keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();cursor=Math.max(0,Math.min(history.length,cursor+(e.key==='ArrowUp'?-1:1)));input.value=history[cursor]||'';}});
    print('Aether Terminal\nType help for virtual filesystem commands.');updatePrompt();return{content,beforeClose:()=>!busy||(services.notify('Wait for the current command to finish.'),false),dispose(){disposed=true;}};
  }});
})();